-- TUTORIAL 18 — migration V1: the whole schema, written by hand.
-- From now on FLYWAY owns the schema. Hibernate only VALIDATES that
-- entities and tables agree (spring.jpa.hibernate.ddl-auto=validate).
-- Written in portable SQL: runs on H2 (dev) and PostgreSQL (prod).
-- A migration is IMMUTABLE once applied: never edit this file again;
-- schema changes go into V2, V3, ... forever.

CREATE TABLE author (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE genre (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE user_account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255),
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE book (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255),
    author_id  BIGINT NOT NULL REFERENCES author (id),
    owner_id   BIGINT REFERENCES user_account (id),
    price      NUMERIC(10, 2),
    cost_price NUMERIC(10, 2),
    -- DEFAULT FALSE: raw-SQL inserts (like V2) no longer need to
    -- name the soft-delete column - the tutorial-11 seeding pain,
    -- fixed at the schema level.
    deleted    BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE book_genre (
    book_id  BIGINT NOT NULL REFERENCES book (id),
    genre_id BIGINT NOT NULL REFERENCES genre (id),
    deleted  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (book_id, genre_id)
);

-- Foreign keys we filter on constantly (tutorial 10's queries).
CREATE INDEX idx_book_author ON book (author_id);
CREATE INDEX idx_book_owner ON book (owner_id);
